import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/Footer.css";
import Logo from "./components/uiPersonalizada/logo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body
    className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
  >
    <main className="flex-1 w-full flex flex-col">
      {children}
    </main>

    <footer className="footer mt-auto p-4 bg-gray-100">
      <div className="social-icons flex gap-4 justify-center">
        <a href="https://twitter.com" aria-label="Twitter" className="hover:text-blue-500">X</a>
        <a href="https://linkedin.com" aria-label="LinkedIn" className="hover:text-blue-700">in</a>
        <a href="https://youtube.com" aria-label="YouTube" className="hover:text-red-600">
          <Logo src="/img/juego.png" alt="YouTube" width={30} height={30} />
        </a>
      </div>
      <p className="text-center text-sm mt-4">Sopra Steria 2025©</p>
    </footer>
  </body>
</html>

  );
}
